# Generated by Django 2.0.5 on 2018-05-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpathyDemo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpathyFigures',
            new_name='SpathyFiguresModel',
        ),
    ]
